name: Run Notebooks

on:
  push:
  pull_request:

jobs:
  test-notebooks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run all notebooks
      run: |
        IFS=$(echo -ne "\n\b") ; 
        for notebook in $(find . -name "*.ipynb" -not -path "./.ipynb_checkpoints/*"); do
          base=$(basename "$notebook" .ipynb)
          output="executed_${base}.ipynb"
          echo "Running $notebook"
          jupyter nbconvert --to notebook --execute "$notebook" --output "$output"
        done
